name: Sync dependencies for GA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs:
  sync:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: sync
        run: bash ./.github/scripts/sync.sh
        env:
          $GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}