name: Sync dependencies for GA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs:
  sync:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: sync
        run: bash ./.github/scripts/sync.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}