name: 'Test Single Formula'
on:
  workflow_dispatch:
    inputs:
      macos:
        description: macOS version
        required: true
      extension:
        description: Extension name
        required: true
jobs:
  get-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get matrix
        id: set-matrix
        run: |
           json_array=()
           extension=${{ github.event.inputs.extension }}
           for formula in ./Formula/$extension@*.rb; do
             json_array+=("{\"php\": \"$(echo $formula | grep -Eo '[0-9]+\.[0-9]+')\", \"extension\": \"$extension\"}")
           done
           echo "matrix={\"include\":[$(echo ${json_array[@]} | sed -e 's|} {|}, {|g')]}" >> "$GITHUB_OUTPUT"
  tests:
    needs: get-matrix
    runs-on: ${{ github.event.inputs.macos }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix )}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup cache environment
        uses: shivammathur/cache-extensions@develop
        env:
          skip_dependency_extensions: true
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ github.event.inputs.extension }}
          key: homebrew-extensions-single-v2
      - name: Setup PHP
        uses: shivammathur/setup-php@develop
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ github.event.inputs.extension }}
      - name: Testing PHP version
        run: |
          php -v
          php -m
      - name: Testing Extensions
        if: github.event.inputs.extension != 'xdebug2'
        run: |
          extension=${extension/pecl_/}
          php -r "if(! extension_loaded('$extension')) {throw new Exception('$extension not found');}"
          php -r "echo '$extension version: ' . phpversion('$extension');"
        env:
          extension: ${{ github.event.inputs.extension }}
      - name: Testing Xdebug2
        if: github.event.inputs.extension == 'xdebug2'
        run: |
          php -r "if(phpversion('xdebug')!='2.9.8') {throw new Exception('xdebug2 not found');}"
          php -r "echo 'xdebug version: ' . phpversion('xdebug');"
