name: 'Test Formulae'
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
  repository_dispatch:
  schedule:
    - cron: '30 4 * * *'
jobs:
  tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
        extensions: ['grpc, pcov, protobuf, swoole, xdebug']
        include:
          - php-versions: '5.6'
            extensions: 'grpc, protobuf, swoole, xdebug'
          - php-versions: '7.0'
            extensions: 'grpc, protobuf, swoole, xdebug'
          - php-versions: '8.0'
            extensions: 'pcov, swoole, xdebug'
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@develop
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ matrix.extensions }}
      - name: Testing PHP version
        run: |
          php -v
          php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"
      - name: Testing Extensions
        run: |
          php -m
          php -r "if(substr(phpversion(), 0, 3)!=8.0 && ! extension_loaded('grpc')) {throw new Exception('grpc not found');}"
          php -r "if(substr(phpversion(), 0, 3)!=8.0 && ! extension_loaded('protobuf')) {throw new Exception('protobuf not found');}"
          php -r "if(phpversion()>=7.1 && ! extension_loaded('pcov')) {throw new Exception('pcov not found');}"
          php -r "if(! extension_loaded('swoole')) {throw new Exception('swoole not found');}"
          php -r "if(! extension_loaded('xdebug')) {throw new Exception('xdebug not found');}"
